### ISSUE TITLE
能放下你们训练出来的权重模型嘛？？

### ISSUE THREAD

**Issue by finetune-master** [imenebak/UAV-Crowd-Counting#1]
你们的代码有些问题
1、Trainval.ipynb中的create_img()函数上面那段代码无法运行.
2、划分的训练集、验证集、测试集是哪些.
3、Trainval.ipynb没有train_sum这个变量，没有定义logging这个变量
4、Trainval.ipynb中img = cv2.resize(target,(int(target.shape[1]//8),int(target.shape[0]//8)),interpolation = cv2.INTER_CUBIC)*64为什么用//

**Comment by imenebak** [comment]
bonjour, je suis tres occupé en ce moment je pourrais pas reprendre mon code. pour tes questions ca se peut que vous trouverez des soucis d'exécution, vérifie ta version python et les versions des framework et bibliothèques. sinon je t'invite a ce documenter sur le model de comptage de foules CSRNET avant de passer au code. pour la phase d'apprentissage nous avant d'utiliser les données d'apprentissage pour l'apprentissage, les données de validation pour vérifier l'apprentissage et les données de test pour tester le model.

**Comment by finetune-master** [comment]
> bonjour, je suis tres occupé en ce moment je pourrais pas reprendre mon code. pour tes questions ca se peut que vous trouverez des soucis d'exécution, vérifie ta version python et les versions des framework et bibliothèques. sinon je t'invite a ce documenter sur le model de comptage de foules CSRNET avant de passer au code. pour la phase d'apprentissage nous avant d'utiliser les données d'apprentissage pour l'apprentissage, les données de validation pour vérifier l'apprentissage et les données de test pour tester le model.

Thanks
