### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [imenebak/UAV-Crowd-Counting#2]
How do we install and run this in the cloud?

**Comment by imenebak** [comment]
Hello, by the cloud do you mean Google Colab ?

**Comment by SureshbabuAkash1999** [comment]
Yes Sir.

**Comment by imenebak** [comment]
Well, first of all I'm a girl haha 
then to answer your question, after having chosen the dataset to use follow this steps:
 - Charge your data from drive, a link or from your disk
 - Clone this repo to Google colab
 - Start executing scripts as mentioned in readme file (you maye need to check your file tree)
If you have any other questions I will be happy to help you

**Comment by imenebak** [comment]
Closed, since no more questions
