### ISSUE TITLE
ValueError: Unknown loss function: accuracy

### ISSUE THREAD

**Issue by karla3jo** [imenebak/UAV-Crowd-Counting#3]
Hello!

First of all, thank you for this detailed walkthrough of your work. It's quite enjoyable to follow in the Colab notebooks :)
I have some doubts in some lines of code in TrainVal notebook and I would really appreciate if you can help me understand what is going on. 

In the definition of the CrowdNet function, there is a line almost at the end stating:
model.compile(optimizer=Adam(1e-5), loss='accuracy', metrics=[mae, "mse"])

However, in the next blocks before fitting the model, it appears another compilation stating:
model.compile(optimizer=Adam(1e-5), loss='mae', metrics=[mae, "mse", 'accuracy'])

Why are they different?
When I check the code for CSRNet, both lines have the same structure:
model.compile(optimizer=sgd, loss=euclidean_distance_loss, metrics=['mse'])

When I try to make both lines equal in Soft-CSRNet, I can't use "accuracy" as loss because it throws the "Unknown loss function" error. I get no errors with "mae" as loss, but then I cannot manage to replicate the same range of values in the Y-axis of the "Training Loss on Dataset" plot. 

Thanks in advance for your support.

**Comment by imenebak** [comment]
Hey Karla,
I'm glad you're having fun experimenting with this repository.
to answer your first question,
I was testing many loss functions during this project to calculate how much Soft_CSRNET should seek to minimize during training. So in Crowdnet's definition I went with this configuration:
model.compile(optimizer=Adam(1e-5), loss='accuracy', metrics=[mae, "mse"])
using "accuracy" as a loss function and both mae (function I defined) and "mse" functions to judge my model performance.
before fitting the model finally as you noticed, I decided to change the loss function to 'mae' and I strongly believe this configuration gave me best results.
By definition, loss function is used to optimize your model (This is the function that will get minimized by the optimizer) while a metric is used to judge the performance of your model (This is only for you to look at and has nothing to do with the optimization process). 

Next, the "unknown loss function" may be a syntax error, I unfortunately don't have more access to the data I used for this project so reproducing this could take me lot of time. I suggest you check that you are up-to-date with the master branch of Keras. or to find a workaround to test it.

I hope this'll help you.
