### ISSUE TITLE
Can u give me ur weights

### ISSUE THREAD

**Issue by VietPT3502** [imenebak/UAV-Crowd-Counting#4]
hi author, i want ur weight for my research. Can u give me ur weight. Tks.

**Comment by imenebak** [comment]
Hi, you can find the weights here [https://drive.google.com/file/d/1-0e0myGYnzm4VxLEM2SP5cgCkIq1F_YK/view?usp=drivesdk]()

**Comment by VietPT3502** [comment]
> Hi, you can find the weights here https://drive.google.com/file/d/1-0e0myGYnzm4VxLEM2SP5cgCkIq1F_YK/view?usp=drivesdk
can u share access for me. I just requested

**Comment by imenebak** [comment]
The link is now available, can you recheck?

**Comment by ahn-family1004** [comment]
Hi
I am testing with your code "[UAV-Crowd-Counting]/Test_model.ipynb"

but,  I can't find  "/content/drive/My Drive/ValTrain/visdr2020/best_weights.h5"  "/content/drive/My Drive/ValTrain/visdr2020/Model.json" 

where can I have best_weights.h5 and  Model.json ?

Additionally, how can you download files from your Google Drive for  [AdaptativeFastDensityVisDrone.ipynb and CrowdVisdrone.ipynb, DensityVisDrone.ipynb, TrainVal.ipynb ?

Your code is very useful for me.

Your answer will help me a lot.

**Comment by imenebak** [comment]
Hey,
I'm not sure anymore if these are the correct files, you can try:
For the weights:
https://drive.google.com/file/d/1-0e0myGYnzm4VxLEM2SP5cgCkIq1F_YK/view?usp=drivesdk

For the model: 
https://drive.google.com/file/d/1-1PbkqmvegKRJ9Hi-rtCAumjTywJyzWk/view?usp=drivesdk

And regarding the .ipynb files, I believe you can download them directly from colab.

I hope this will help.

**Comment by ahn-family1004** [comment]
*First of all, thank you for your reply.*

I tried to contact
https://drive.google.com/file/d/1-1PbkqmvegKRJ9Hi-rtCAumjTywJyzWk/view?usp=drivesdk
for
the model.
but, I have a message " Access permission required" in Google Drive.

I want to requesting access permission
I know you are very busy, but please reply
(Access permission or attached model.json)


2025년 1월 22일 (수) 오전 5:34, Imene ***@***.***>님이 작성:
